port = 3306
host = false
bind = "0.0.0.0"
language = "english"
root_password = ""
app_username = "wordpress"
app_password = "ThisIsPassword"
app_database="wordpress"
password_column_name = "authentication_string"
